<?php

declare(strict_types=1);

namespace App\Enums;

enum MatchResults: string
{
    case ORDER_NOT_OPEN_OR_INVALID = 'ORDER_NOT_OPEN_OR_INVALID';
    case NO_COUNTER_ORDER = 'NO_COUNTER_ORDER';
    case AMOUNTS_NOT_EQUAL = 'AMOUNTS_NOT_EQUAL';
    case BUYER_NOT_FOUND = 'BUYER_NOT_FOUND';
    case INSUFFICIENT_BUYER_FUNDS = 'INSUFFICIENT_BUYER_FUNDS';
    case INSUFFICIENT_SELLER_ASSET_LOCKED = 'INSUFFICIENT_SELLER_ASSET_LOCKED';
}
